### ISSUE TITLE
update: nvalt-notational-velocity-atom.md

### ISSUE THREAD

**Issue by viddo** [xHN35RQ/faq#1]
Hi there!
I read http://faq.surge.sh/nvalt-notational-velocity-atom/#room-for-improvement and as the author of the referenced package in the 2nd paragraph I found it particularly interesting, and was curious about some things you stated there:

> …
> https://github.com/viddo/atom-textual-velocity offers some interesting solutions within a single Atom package, and is worth trying out. This won’t be a fit for everyone. I for example do not like the nvALT layout of a constantly visible note list. 

Did you know that you can hide/show the notes list panel through the _toggle panel_ command/ [cmd+shift+C shortcut](https://github.com/viddo/atom-textual-velocity/blob/master/keymaps/textual-velocity.cson#L2)?

> …
> And I also prefer an approach that slowly extends Atom’s basic functionality towards nvALT in small iterative steps, asking “Why does this work? How can it work better? Is it necessary?” at each step, instead of duplicating exactly nvALT within Atom. Perhaps there are some nvALT functionalities that can be improved upon, and we’ll miss the opportunity for improvements and simplifications if we simply copy-exact without careful thought and iterative testing.

Actually, the sentiment written in this paragraph matches my thoughts too. Atom has a different environment and goals, and of course that should be leveraged. That said, my decisions are likely not the best at all times, if you (or anyone else reading this) think there are things that could/should be done differently and better please do let me know! I'd be happy for more people getting involved in the project, feel free to file issues or contact me if you want to continue a conversation. :)

**Comment by xHN35RQ** [comment]
Thanks for your thoughts! I wrote this section several months ago when your package was new. I've changed my mind regarding your package as I've had a chance to test it earlier this week. I am working on updating the article.

**Comment by xHN35RQ** [comment]
also @viddo, thanks for reading and thanks for your comments. I appreciate it! :+1:

**Comment by xHN35RQ** [comment]
@viddo I've updated the article, thanks again for your thoughts.
