### ISSUE TITLE
Atom considered harmful

### ISSUE THREAD

**Issue by DivineDominion** [xHN35RQ/faq#2]
With your recent findings (although others seem to know about it, they were new to me!), it may be a good idea to add a word of warning in <https://github.com/xHN35RQ/faq/blob/master/docs/nvalt-notational-velocity-atom.md>  :)

**Comment by xHN35RQ** [comment]
thanks for reminding me. nuked all references to atom in https://github.com/xHN35RQ/faq/commit/fa97c35aac1bda8d21cb00c2daf636e2b7ad599d

**Comment by xHN35RQ** [comment]
and added something useful: https://github.com/xHN35RQ/faq/commit/286775e862223fd1427375ca02f05b884ec4c259 😉

**Comment by DivineDominion** [comment]
Ha! Great :)
